// COCO Design style reminder: project detail pages extend the same quiet editorial
// language while adding enough evidence to make a high-consideration decision feel safe.
import { ArrowLeft, ArrowUpRight } from "lucide-react";
import { Link, useRoute } from "wouter";

const projects: Record<string, { type: string; title: string; meta: string; image: string; intro: string; body: string; gallery: string[] }> = {
  "light-drawn-family-lounge": { type: "Residential renovation / Living", title: "Light-drawn family lounge", meta: "128 sqm / Shanghai / 2024", image: "/manus-storage/coco-project-living-original_42028b94.png", intro: "A soft renovation organized around daylight, oak, and low sculptural furniture.", body: "The plan opens the family room toward the light and lets storage become part of the architecture. A restrained palette gives the room enough texture to feel lived in, while the low furniture keeps sightlines open from morning to evening.", gallery: ["/manus-storage/coco-living_d389328c.png", "/manus-storage/coco-project-living-original_42028b94.png"] },
  "city-kitchen-evening-light": { type: "Apartment design / Dining", title: "City kitchen with quiet evening light", meta: "96 sqm / Shanghai / 2024", image: "/manus-storage/coco-project-dining-original_1c86ecd9.png", intro: "A compact city home shaped by warm task lighting and dark wood rhythm.", body: "The kitchen and dining space are designed as one continuous atmosphere. Dark timber brings depth to the compact plan, while practical task lighting allows the room to shift from a focused morning to a slow evening meal.", gallery: ["/manus-storage/coco-dining_5bab11a1.png", "/manus-storage/coco-project-dining-original_1c86ecd9.png"] },
  "textured-bedroom-retreat": { type: "Primary suite / Bedroom", title: "Textured bedroom retreat", meta: "42 sqm / Shanghai / 2024", image: "/manus-storage/coco-project-bedroom-original_33a24536.png", intro: "A calm suite using plaster, linen, and integrated storage to reduce visual noise.", body: "The bedroom is treated as a quiet threshold between the activity of the home and the slower rhythm of rest. Integrated storage removes visual noise, while plaster and linen bring softness without adding decoration for its own sake.", gallery: ["/manus-storage/coco-bedroom_33e2ceb8.png", "/manus-storage/coco-project-bedroom-original_33a24536.png"] },
};

export default function ProjectDetail() {
  const [, params] = useRoute<{ slug: string }>("/works/:slug");
  const project = params ? projects[params.slug] : undefined;
  if (!project) return <div className="not-found"><h1>404</h1><p>This project is not available yet.</p><Link className="button button-dark" href="/works"><ArrowLeft size={14} /> Back to works</Link></div>;
  return <div className="detail-page"><section className="detail-intro"><div><Link className="text-link" href="/works"><ArrowLeft size={14} /> Back to works</Link><div className="section-label" style={{ marginTop: "4rem" }}>{project.type}</div></div><div><h1>{project.title}</h1><p>{project.intro}</p><div className="project-meta" style={{ marginTop: "22px", justifyContent: "flex-start" }}><span>{project.meta}</span></div></div></section><img className="detail-hero-image" src={project.image} alt={project.title} /><section className="detail-body"><div className="section-label">The approach</div><div className="detail-copy"><h2>Less noise.<br />More life.</h2><p>{project.body}</p><Link className="text-link" style={{ marginTop: "30px" }} href="/contact">Start a project <ArrowUpRight size={14} /></Link><div className="detail-gallery">{project.gallery.map((image) => <img src={image} alt="Interior detail" key={image} />)}</div></div></section></div>;
}
